---
title: "Additional Resources"
---

You may find the following resources useful:

- [Official PrairieLearn Documentation](https://docs.prairielearn.com/)
    - [Getting Started](https://docs.prairielearn.com/getting-started/) - a more detailed walkthrough of the ideas covered in this guide.
    - [Case Studies](https://www.prairielearn.com/research) - links to research papers on various topics related to pedagogical best practices with PrairieLearn
- You are welcome to use / copy / adapt the following student-facing resources for your own courses:
    - [EECS 183 PrairieLearn Tutorial](https://py183.eecs.umich.edu/tutorials/prairielearn/prairielearn.html)
    - [EECS 183 PrairieTest Tutorial](https://py183.eecs.umich.edu/tutorials/prairietest/prairietest.html)
    - [EECS 183 Exam Details](https://py183.eecs.umich.edu/docs/exams.html)
- Several question types are illustrated in the assessments of this [demo course](https://us.prairielearn.com/pl/course_instance/197326/assessments).
- For further examples of question generation, you may find useful this [Engineering Education Innovation day presentation](https://drive.google.com/drive/folders/1Cem9CCpgCb1zEnu-cQtDEVyIUjDvIEt4?usp=drive_link) by Laura Alford and Steven Bogaerts. It includes illustration of question generation through both the web interface and the repository interface. You can also find a [video recording of the presentation](https://eei.engin.umich.edu/eei-days-2026/session-list-2026/). 

Contact info:

- [etf-advisor@umich.edu](mailto:etf-advisor@umich.edu) - for questions on Prairie*Learn*
- [etf-support@umich.edu](mailto:etf-support@umich.edu) - for questions on Prairie*Test* and the ETF
