---
title: "Web Interface"
---

Once you [gain access to PrairieLearn](index.qmd#access), read the following sections describing first steps for working with its web interface.

## Making Your First PrairieLearn Question {#question}

### Entering an AI Prompt

Log in to the [PrairieLearn course site](https://us.prairielearn.com/) and navigate to your course. Click on "Questions" in the left-hand navigation menu. Then click the "Add questions" drop-down and choose "Generate question with AI". Enter whatever details of a question you'd like. For a simple first example, you might consider: "Show a randomly generated linear equation and a random x value. Students must enter (short-answer) the resulting y value." The AI will process for a bit and then generate a question you can try out in the "Preview" tab.

### Adjusting the Question with AI

With the initial draft question generated, you can chat with the AI to adjust it as needed. When you are satisfied with the question, click "Finalize question". Give it a title (student-facing) and a QID (question ID). The QID must be unique within your course. Click "Finalize question" again.

### Exploring the Question

Click on the questions tab, and click the link for the question you just made. It will open in the "Preview" tab, where you can try it out again. Click on the "Settings" tab for the question and note what's available. Also briefly check out the "Files" tab, and you'll see that there are three files associated with your question:

- `info.json` - contains basic settings for your question, in JSON format
- `question.html` - defines what the question looks like to students, in HTML format
- `server.py` - defines how the question is generated, in Python code

Only minimal JSON and HTML knowledge is needed, if any. For Python, more can be helpful, but you can also manage with little or none if you use AI to help you.

## Making Your First Assessment

In PrairieLearn, an "assessment" is a collection of questions that students will answer. There are two types of assessments, "Homework" and "Exam". The type determines some default settings, but these can be adjusted anytime. When you're ready to make an exam to be administered in the ETF, you'll make an assessment of type "Exam" and then follow ETF procedures. <!-- TO DO link -->

### Creating an Empty Assessment

To make your first assessment, click on "Assessments" in the left-hand navigation menu. Then click the "Add assessment" button. Let's give it the title "Homework 1", short name "hw1", set the type to "Homework", and the "set" to whatever you'd like. (You can also edit the available assessment sets in Course Settings, Assessment Sets.) Press the "Create" button.

### Adding Questions to the Assessment

You'll see your new assessment's page. There are no questions in it yet, so click "Add questions". You'll see "Zone 1". In the right panel, you can click your question (not the blue underlined link, but the box around the question) to add it to the assessment.

Hit the blue disk icon button (labeled "Save" on hover) to save, and you'll be back in your Assessment.

Go back to the Questions page and make a few more questions, so that you have a few to try out the assessment functionality with. Then add them to your assessment.

### Exploring the Assessment

When looking at your assessment page, you can try it out as a student will see it by clicking on your name in the upper-right corner and choosing "Student view without access restrictions".

When you're done exploring it, go back to the regular view (upper-right corner, "Staff view"). Click the other tabs at top to explore what's possible, such as the "Access" tab, "Files", "Manual grading", "Settings", etc.

## Importing Content from Canvas

If you have quizzes on Canvas that you'd like to import into PrairieLearn, there is a convenient way to do that. For details, visit the official documentation on [Importing content from other platforms](https://docs.prairielearn.com/importingContent/).

## Adding a Standard Notes Page to Your Assessment

PrairieLearn enables you to add files to an assessment that students will be allowed to access. This could be a reference / formula / "cheat" sheet, for example.

### Uploading the Reference Sheet

Suppose you have a `reference.pdf` file you want students to be able to access during the exam. First, we need to provide the file to PrairieLearn:

- In the left sidebar, choose "Assessments" and click on the assessment you want to add the file to.
- Click on the "Files" tab and hit the "Add new client files" button.
- Upload your `reference.pdf` file via the file dialog that appears.
- In the "Files" window, you should now see a new folder named "clientFilesAssessment". If you click on that folder, you should see the `reference.pdf` file inside. You can click on it to verify that it's the correct file.

### Adding a Link to the Reference Sheet in the Assessment

Next, we need to give students access to the file in the assessment itself:

- Still in the "Files" tab for the assessment, click the `edit` button for the file `infoAssessment.json` to open it in an in-browser editor.
- We need to add one entry to the file: a `"text"` field containing a link to the file and any accompanying text we want. The `"text"` field must be valid HTML, and the file accessed via the URL `{{{ client_files_assessment }}}/reference.pdf` (or adjust for your file name). The `{{{ client_files_assessment }}}` is a placeholder that PrairieLearn will replace with the correct URL for the assessment's files. For example:
    - Suppose you want your "Quiz 1" assessment to allow access to a `reference.pdf` file you've created.
    - When you open `infoAssessment.json`, you'll see something like this:

    ```json
    {
    "uuid": "some unique identifier here",
    "type": "Exam",
    "title": "Quiz 1",
    "set": "Quizzes",
    ... (more settings omitted for brevity) ...
    }
    ```

    Add a new line for the "text" field. Anywhere is fine. For example, see below:

    ```json
    {
    "uuid": "some unique identifier here",
    "type": "Exam",
    "title": "Quiz 1",
    "text": "<p><a href=\"{{ client_files_assessment }}/reference.pdf\">Click here for the exam reference sheet</a>. You may find it convenient to open this document in a new browser tab.</p>",
    "set": "Quizzes",
    ... (more settings omitted for brevity) ...
    }
    ```

    Note the HTML syntax, the use of `"` and `\"`, and the `,` at the end. Such syntax is required. The following is just that line, which you can easily copy by hovering your mouse over the box and clicking the clipboard icon in the upper-right corner:

    ```json
    "text": "<p><a href=\"{{ client_files_assessment }}/reference.pdf\">Click here for the exam reference sheet</a>. You may find it convenient to open this document in a new browser tab.</p>",
    ```

- You may need to adjust the file name if yours is not called `reference.pdf`, and you may also wish to change the wording.
- Click the `Save` button when you are finished editing.

With the changes above, students will see a link to the `reference.pdf` file when they open the assessment. I recommend you test this out with the "Student view without access restrictions" option to verify that it works as needed.

## Allowing Students to Add a Custom Notes Page to Your Assessment

::: {.callout-note appearance="simple" title="Acknowledgment"}
Thank you to the University of California - San Diego, Triton Testing Center, for their [documentation](https://tritontesting.ucsd.edu/computer-based-testing/instructors/Digital-Note-Sheet-Method_CBTF_SP25-1.pdf#:~:text=Allowing%20access%20to%20student%20created%20digital%20notes,sample%20code%20for%20the%20question.html%20and%20the.) on this topic, which served as the basis for the documentation below.
:::

In some cases, rather than preparing a reference sheet yourself, you may want students to prepare their own reference sheet. However, please note: in the ETF, for reasons of exam security (especially when multiple courses' exams are administered simultaneously), students are never allowed to bring in physical copies of their own reference sheets. Thus, if you want students to be able to use their own personally-prepared reference sheets during an exam, we need to set up PrairieLearn to allow this.

Details coming soon!

